export default {
    log:{
        eventKey:"click",
        method(eventValue,e,vm){
            console.log(eventValue,e,vm);
        }
    },
    nextPage:{
        eventKey:"click",
        method(eventProps,eventObj,vm){
            vm.$store.dispatch('currentRenderState/nextPage')
        }
    },
    prePage:{
        eventKey:"click",
        method(eventProps,eventObj,vm){
            vm.$store.commit("currentRenderState/prePage");
        }
    }
}