// 放大缩小步数
export const SCALE_STEP = 0.15;
// 画布距离边框最小距离
export const CONTENT_OFFSET = 35;
// 旋转吸附值
export const ROTATE_ADSORBENT_VALUE = 5;
// 默认辅助线网格大小
export const DEFAULT_GRID_GUIDE_OFFSET = 40;
// 辅助线吸附值
export const GRID_ADSORBENT_VALUE = 5;


export const COMMAND_UPDATE_SELECT_ITEM = 'COMMAND_UPDATE_SELECT_ITEM';
export const COMMAND_UPDATE_MULTIPLE_SELECT_ITEM = 'COMMAND_UPDATE_MULTIPLE_SELECT_ITEM';
export const COMMAND_SELECT_COMPONENT = 'COMMAND_SELECT_COMPONENT';
export const COMMAND_SELECT_MULTIPLE_COMPONENT = 'COMMAND_SELECT_MULTIPLE_COMPONENT';
export const COMMAND_SELECT_CONTAINER = 'COMMAND_SELECT_CONTAINER';
export const COMMAND_SELECT_PAGE = 'COMMAND_SELECT_PAGE';
export const COMMAND_SELECT_SIBLING_PAGE = 'COMMAND_SELECT_SIBLING_PAGE';
export const COMMAND_CLEAR_CURRENT_TARGET = 'COMMAND_CLEAR_CURRENT_TARGET';
export const COMMAND_UPDATE_CANVAS_SIZE = 'COMMAND_UPDATE_CANVAS_SIZE';
