export const SCALE_STEP = 0.15;
export const CONTENT_OFFSET = 35;
export const ROTATE_ADSORBENT_VALUE = 5;

export const COMMAND_UPDATE_SELECT_ITEM = 'COMMAND_UPDATE_SELECT_ITEM';
export const COMMAND_SELECT_COMPONENT = 'COMMAND_SELECT_COMPONENT';
export const COMMAND_SELECT_CONTAINER = 'COMMAND_SELECT_CONTAINER';
export const COMMAND_SELECT_PAGE = 'COMMAND_SELECT_PAGE';
export const COMMAND_SELECT_SIBLING_PAGE = 'COMMAND_SELECT_SIBLING_PAGE';
export const COMMAND_CLEAR_CURRENT_TARGET = 'COMMAND_CLEAR_CURRENT_TARGET';
