// 更新scale
export const CHANGE_SCALE = 'CHANGE_SCALE';
// 更新选中框
export const UPDATE_SELECT_INFO = 'UPDATE_SELECT_INFO';
export const UPDATE_CANVAS_SIZE = 'UPDATE_CANVAS_SIZE';
export const BEFORE_DELETE_COMPONENT = 'BEFORE_DELETE_COMPONENT';
// 保存
export const SUBMIT_PROJECT = 'SUBMIT_PROJECT';