// 新增页面
export const ADD_PAGE = 'ADD_PAGE';
// 删除页面
export const DELETE_PAGE = 'DELETE_PAGE';
// 新增组件
export const ADD_COMPONENT = 'ADD_COMPONENT';
// 删除组件
export const DELETE_COMPONENT = 'DELETE_COMPONENT';
// 修改组件属性
export const UPDATE_COMPONENT_PROPS = 'UPDATE_COMPONENT_PROPS';
// 修改组件大小
export const BEFORE_UPDATE_COMPONENT_SIZE = 'BEFORE_UPDATE_COMPONENT_SIZE';
export const UPDATING_COMPONENT_SIZE = 'UPDATING_COMPONENT_SIZE';
export const AFTER_UPDATE_COMPONENT_SIZE = 'AFTER_UPDATE_COMPONENT_SIZE';
// 修改组件位置
export const BEFORE_UPDATE_COMPONENT_POSITION = 'BEFORE_UPDATE_COMPONENT_POSITION';
export const UPDATING_COMPONENT_POSITION = 'UPDATING_COMPONENT_POSITION';
export const AFTER_UPDATE_COMPONENT_POSITION = 'AFTER_UPDATE_COMPONENT_POSITION';
// 调换组件index
export const SWITCH_INDEX = 'SWITCH_INDEX';
// 修改组件index最上
export const UPDATE_INDEX_TO_TOP = 'UPDATE_INDEX_TO_TOP';
// 修改组件index最下
export const UPDATE_INDEX_TO_BOTTOM = 'UPDATE_INDEX_TO_BOTTOM';
